/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Travel Plan
         * @description Generate initial travel plan using Planner Agent.
         *
         *     This endpoint uses LangGraph-based Planner Agent to:
         *     1. Parse user request and extract structured information
         *     2. Fetch relevant venues using vector search (SEO-33)
         *     3. Generate comprehensive day-by-day itinerary
         *     4. Validate budget and time constraints
         *     5. Optionally save the plan to database (default: True)
         *
         *     Frontend usage:
         *     ```javascript
         *     // Generate plan and save to DB (default)
         *     const response = await fetch('/api/ai/plans/generate?user_id=1', {
         *       method: 'POST',
         *       body: JSON.stringify({
         *         user_request: "3일 서울 여행",
         *         start_date: "2025-07-01",
         *         end_date: "2025-07-03",
         *         budget: 500000,
         *         interests: ["palace", "food"]
         *       })
         *     });
         *
         *     // Generate plan without saving
         *     const response = await fetch('/api/ai/plans/generate?user_id=1&save_to_db=false', {
         *       method: 'POST',
         *       body: JSON.stringify({ ... })
         *     });
         *     ```
         *
         *     Args:
         *         request: Travel plan generation request
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         save_to_db: Whether to save the generated plan to database (default: True)
         *         db: Database session
         *
         *     Returns:
         *         TravelPlanResponse with generated plan and optional plan_id if saved
         */
        post: operations["generate_travel_plan_api_ai_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/plans/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Travel Plan
         * @description Review and modify travel plan using Reviewer Agent.
         *
         *     This endpoint uses LangGraph-based Reviewer Agent to:
         *     1. Parse user feedback (approve/reject/modify)
         *     2. Modify specific sections of the plan
         *     3. Validate modified plan consistency
         *
         *     Request body should include the original plan in the request.
         */
        post: operations["review_travel_plan_api_ai_plans_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login and get access token.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current authenticated user.
         */
        get: operations["get_current_user_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description List all travel plans for current user.
         *
         *     Args:
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         db: Database session
         *
         *     Returns:
         *         List of travel plans
         */
        get: operations["list_plans_api_plans__get"];
        put?: never;
        /**
         * Create Plan
         * @description Create a new travel plan from Planner Agent response.
         *
         *     **Note**: Consider using POST /save endpoint for clearer intent.
         *
         *     Args:
         *         plan: PlannerPlan data from frontend
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         db: Database session
         *
         *     Returns:
         *         Created travel plan
         *
         *     Raises:
         *         HTTPException: 400 if validation fails, 500 if database error
         */
        post: operations["create_plan_api_plans__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Planner Plan
         * @description Save a plan generated by Planner Agent to database.
         *
         *     This endpoint is specifically designed for saving plans from the Planner Agent.
         *     The plan structure matches the PlannerPlanCreate schema which includes:
         *     - Daily itinerary with activities
         *     - Accommodation information
         *     - Cost breakdown
         *     - Plan summary
         *
         *     Frontend usage:
         *     ```javascript
         *     // After getting plan from /api/ai/plans/generate
         *     const response = await fetch('/api/plans/save', {
         *       method: 'POST',
         *       body: JSON.stringify(plannerPlan),
         *       params: { user_id }
         *     });
         *     ```
         *
         *     Args:
         *         plan: Plan data from Planner Agent
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         db: Database session
         *
         *     Returns:
         *         Saved travel plan with database ID
         *
         *     Raises:
         *         HTTPException: 400 if validation fails, 500 if database error
         */
        post: operations["save_planner_plan_api_plans_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description Get a specific travel plan.
         *
         *     Args:
         *         plan_id: Plan ID
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         db: Database session
         *
         *     Returns:
         *         Travel plan details
         *
         *     Raises:
         *         HTTPException: 404 if plan not found
         */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Plan
         * @description Delete a travel plan.
         *
         *     Args:
         *         plan_id: Plan ID
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         db: Database session
         *
         *     Returns:
         *         Success message
         *
         *     Raises:
         *         HTTPException: 404 if plan not found
         */
        delete: operations["delete_plan_api_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Plan
         * @description Update a travel plan.
         *
         *     Args:
         *         plan_id: Plan ID
         *         plan: Update data
         *         user_id: User ID (temporary: will be replaced with authentication)
         *         db: Database session
         *
         *     Returns:
         *         Updated travel plan
         *
         *     Raises:
         *         HTTPException: 404 if plan not found, 400 if validation fails
         */
        patch: operations["update_plan_api_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_review_travel_plan_api_ai_plans_review_post */
        Body_review_travel_plan_api_ai_plans_review_post: {
            request: components["schemas"]["ReviewTravelPlanRequest"];
            /** Original Plan */
            original_plan: {
                [key: string]: unknown;
            };
        };
        /**
         * GenerateTravelPlanRequest
         * @description Request schema for generating travel plan.
         */
        GenerateTravelPlanRequest: {
            /** User Request */
            user_request: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Budget */
            budget?: number | null;
            /**
             * Interests
             * @default []
             */
            interests: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlannerAccommodation
         * @description Accommodation information.
         */
        PlannerAccommodation: {
            /**
             * Name
             * @description Accommodation name
             */
            name: string;
            /**
             * Cost Per Night
             * @description Cost per night in KRW
             */
            cost_per_night: number;
            /**
             * Total Nights
             * @description Total number of nights
             */
            total_nights: number;
        };
        /**
         * PlannerActivity
         * @description Activity in a day's itinerary.
         */
        PlannerActivity: {
            /**
             * Time
             * @description Time in HH:MM format
             */
            time: string;
            /**
             * Venue Name
             * @description Name of the venue
             */
            venue_name: string;
            /**
             * Venue Type
             * @enum {string}
             */
            venue_type: "attraction" | "restaurant" | "accommodation" | "cafe" | "shopping";
            /**
             * Duration Minutes
             * @description Duration in minutes (max 24 hours)
             */
            duration_minutes: number;
            /**
             * Estimated Cost
             * @description Estimated cost in KRW
             */
            estimated_cost: number;
            /**
             * Notes
             * @description Additional notes
             */
            notes?: string | null;
        };
        /**
         * PlannerDayItinerary
         * @description Single day itinerary.
         */
        PlannerDayItinerary: {
            /**
             * Day
             * @description Day number (starts from 1)
             */
            day: number;
            /**
             * Date
             * @description Date in YYYY-MM-DD format
             */
            date: string;
            /**
             * Theme
             * @description Theme for the day
             */
            theme: string;
            /**
             * Activities
             * @description List of activities
             */
            activities?: components["schemas"]["PlannerActivity"][];
            /**
             * Daily Cost
             * @description Total cost for the day in KRW
             */
            daily_cost: number;
        };
        /**
         * PlannerPlanCreate
         * @description Schema for creating a plan from Planner Agent response.
         */
        PlannerPlanCreate: {
            /**
             * Title
             * @description Plan title
             */
            title: string;
            /**
             * Total Days
             * @description Total number of days (max 30)
             */
            total_days: number;
            /**
             * Total Cost
             * @description Total estimated cost in KRW
             */
            total_cost: number;
            /**
             * Itinerary
             * @description Daily itinerary (at least 1 day)
             */
            itinerary: components["schemas"]["PlannerDayItinerary"][];
            /** @description Accommodation information */
            accommodation?: components["schemas"]["PlannerAccommodation"] | null;
            /**
             * Summary
             * @description Plan summary
             */
            summary?: string | null;
        };
        /**
         * ReviewTravelPlanRequest
         * @description Request schema for reviewing/modifying travel plan.
         */
        ReviewTravelPlanRequest: {
            /** User Feedback */
            user_feedback: string;
            /**
             * Iteration
             * @default 0
             */
            iteration: number;
        };
        /**
         * Token
         * @description Token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TravelPlanUpdate
         * @description Travel plan update schema.
         */
        TravelPlanUpdate: {
            /**
             * Title
             * @description Plan title
             */
            title?: string | null;
            /**
             * Description
             * @description Plan description
             */
            description?: string | null;
            /**
             * Itinerary
             * @description Updated itinerary
             */
            itinerary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Recommendations
             * @description Updated recommendations
             */
            recommendations?: {
                [key: string]: unknown;
            } | null;
            /**
             * Start Date
             * @description Start date of the trip
             */
            start_date?: string | null;
            /**
             * End Date
             * @description End date of the trip
             */
            end_date?: string | null;
        };
        /**
         * UserCreate
         * @description User creation schema.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * UserLogin
         * @description User login schema.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description User response schema.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * TravelPlanResponse
         * @description Response schema for travel plan.
         */
        app__ai__ai_schemas__TravelPlanResponse: {
            /** Plan Id */
            plan_id?: number | null;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
        };
        /**
         * TravelPlanResponse
         * @description Travel plan response schema.
         */
        app__plan__plan_schemas__TravelPlanResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Itinerary */
            itinerary?: {
                [key: string]: unknown;
            } | null;
            /** Recommendations */
            recommendations?: {
                [key: string]: unknown;
            } | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_travel_plan_api_ai_plans_generate_post: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
                /** @description Whether to save the generated plan to database */
                save_to_db?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTravelPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__ai__ai_schemas__TravelPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_travel_plan_api_ai_plans_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_review_travel_plan_api_ai_plans_review_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__ai__ai_schemas__TravelPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_plans_api_plans__get: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__plan__plan_schemas__TravelPlanResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_plans__post: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__plan__plan_schemas__TravelPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_planner_plan_api_plans_save_post: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__plan__plan_schemas__TravelPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
            };
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__plan__plan_schemas__TravelPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_plans__plan_id__delete: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
            };
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_plans__plan_id__patch: {
        parameters: {
            query: {
                /** @description User ID (임시: 나중에 인증으로 대체) */
                user_id: number;
            };
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelPlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__plan__plan_schemas__TravelPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
