"""Add Venue model

Revision ID: 0ef1d64110e5
Revises: 
Create Date: 2025-11-06 22:18:03.943328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0ef1d64110e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('new_address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('x_coord', sa.Float(), nullable=True),
    sa.Column('y_coord', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('operating_days', sa.String(), nullable=True),
    sa.Column('closed_days', sa.String(), nullable=True),
    sa.Column('business_status', sa.String(), nullable=True),
    sa.Column('subway_info', sa.Text(), nullable=True),
    sa.Column('extra_info', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_status', 'venues', ['category', 'business_status'], unique=False)
    op.create_index(op.f('ix_venues_business_status'), 'venues', ['business_status'], unique=False)
    op.create_index(op.f('ix_venues_category'), 'venues', ['category'], unique=False)
    op.create_index(op.f('ix_venues_external_id'), 'venues', ['external_id'], unique=True)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_external_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_category'), table_name='venues')
    op.drop_index(op.f('ix_venues_business_status'), table_name='venues')
    op.drop_index('idx_category_status', table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
